# Generated by Django 4.2.4 on 2023-08-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_biography_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='biography',
            name='status',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Status Date')),
                ('status', models.CharField(choices=[('S', 'Started'), ('P', 'Paused'), ('F', 'Finished')], default='S', max_length=1)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.biography')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='biography',
            name='versions',
            field=models.ManyToManyField(to='main_app.version'),
        ),
    ]
